2023-08-23 00:59:20,249 ERROR: Exception on /login [GET] [in /Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/maxbakaiev/Apps/headnote/app/routes.py", line 70, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/maxbakaiev/Apps/headnote/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/maxbakaiev/Apps/headnote/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/maxbakaiev/Apps/headnote/app/templates/login.html", line 25, in block 'content'
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/werkzeug/routing/map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
2023-08-23 00:59:23,716 ERROR: Exception on /login [GET] [in /Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/maxbakaiev/Apps/headnote/app/routes.py", line 70, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/maxbakaiev/Apps/headnote/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/maxbakaiev/Apps/headnote/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/maxbakaiev/Apps/headnote/app/templates/login.html", line 25, in block 'content'
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/werkzeug/routing/map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
2023-08-23 01:00:03,116 INFO: Headnote startup [in /Users/maxbakaiev/Apps/headnote/app/__init__.py:45]
2023-08-23 01:00:07,944 ERROR: Exception on /login [GET] [in /Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/maxbakaiev/Apps/headnote/app/routes.py", line 70, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/maxbakaiev/Apps/headnote/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/maxbakaiev/Apps/headnote/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/maxbakaiev/Apps/headnote/app/templates/login.html", line 25, in block 'content'
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/werkzeug/routing/map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
