2023-08-22 23:01:50,865 INFO: Microblog startup [in /Users/maxbakaiev/Apps/headnote/app/__init__.py:43]
2023-08-22 23:04:22,311 INFO: Microblog startup [in /Users/maxbakaiev/Apps/headnote/app/__init__.py:43]
2023-08-22 23:19:43,700 INFO: Microblog startup [in /Users/maxbakaiev/Apps/headnote/app/__init__.py:43]
2023-08-22 23:19:51,588 INFO: Microblog startup [in /Users/maxbakaiev/Apps/headnote/app/__init__.py:43]
2023-08-22 23:31:48,995 INFO: Microblog startup [in /Users/maxbakaiev/Apps/headnote/app/__init__.py:43]
2023-08-22 23:32:01,942 INFO: Microblog startup [in /Users/maxbakaiev/Apps/headnote/app/__init__.py:43]
2023-08-22 23:37:22,561 INFO: Microblog startup [in /Users/maxbakaiev/Apps/headnote/app/__init__.py:43]
2023-08-22 23:42:24,031 INFO: Microblog startup [in /Users/maxbakaiev/Apps/headnote/app/__init__.py:43]
2023-08-22 23:53:44,499 INFO: Microblog startup [in /Users/maxbakaiev/Apps/headnote/app/__init__.py:43]
2023-08-23 00:00:00,940 INFO: Microblog startup [in /Users/maxbakaiev/Apps/headnote/app/__init__.py:43]
2023-08-23 00:00:16,769 ERROR: Exception on /index [GET] [in /Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/maxbakaiev/Apps/headnote/app/routes.py", line 21, in index
    form = PostForm()
NameError: name 'PostForm' is not defined
2023-08-23 00:01:26,783 ERROR: Exception on /explore [GET] [in /Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/maxbakaiev/Apps/headnote/app/routes.py", line 36, in explore
    posts = Post.query.order_by(Post.timestamp.desc()).all()
NameError: name 'Post' is not defined
2023-08-23 00:01:27,995 ERROR: Exception on /index [GET] [in /Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/maxbakaiev/Apps/headnote/app/routes.py", line 21, in index
    form = PostForm()
NameError: name 'PostForm' is not defined
2023-08-23 00:01:28,877 ERROR: Exception on /explore [GET] [in /Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/maxbakaiev/Apps/headnote/app/routes.py", line 36, in explore
    posts = Post.query.order_by(Post.timestamp.desc()).all()
NameError: name 'Post' is not defined
2023-08-23 00:02:30,848 INFO: Microblog startup [in /Users/maxbakaiev/Apps/headnote/app/__init__.py:43]
2023-08-23 00:02:36,117 ERROR: Exception on /explore [GET] [in /Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/maxbakaiev/Apps/headnote/app/routes.py", line 36, in explore
    posts = Post.query.order_by(Post.timestamp.desc()).all()
NameError: name 'Post' is not defined
2023-08-23 00:02:37,401 ERROR: Exception on /explore [GET] [in /Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/maxbakaiev/Apps/headnote/app/routes.py", line 36, in explore
    posts = Post.query.order_by(Post.timestamp.desc()).all()
NameError: name 'Post' is not defined
2023-08-23 00:02:39,404 ERROR: Exception on /index [GET] [in /Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/maxbakaiev/Apps/headnote/venv/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/maxbakaiev/Apps/headnote/app/routes.py", line 21, in index
    form = PostForm()
NameError: name 'PostForm' is not defined
